apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-kafka1-kafka-0 
  annotations:
    snapshot.alpha.kubernetes.io/snapshot: snapshot-data-kafka1-kafka-0
spec:
  storageClassName: openebs-standard
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
