apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: kafka1
spec:
  kafka:
    version: 2.1.0
    replicas: 3
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.1"
      delete.topic.enable: "true"
    storage:
      type: persistent-claim
      size: 5Gi
      deleteClaim: true
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 2Gi
      deleteClaim: true
  entityOperator:
    topicOperator: {}
    userOperator: {}

