apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snapshot-data-kafka1-zookeeper-0 
  annotations:
    snapshot.alpha.kubernetes.io/snapshot: snapshot-data-kafka1-zookeeper-0
spec:
  storageClassName: openebs-snapshot-promoter
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
